# Use whichever host key dropbear-hostkey chose (see dropbearkey-data.conf).
[Unit]
Requires=dropbearkey.service
After=dropbearkey.service

[Service]
ExecStart=
ExecStart=-/usr/sbin/dropbear -i -r /run/dropbear-hostkey/dropbear_rsa_host_key $DROPBEAR_EXTRA_ARGS
